import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page.goto("https://admissions-admin.masaischool.com/support-slot")
    page.get_by_role("button", name="Course Management").click()
    page.get_by_role("link", name="Cohort Management").click()
    page.get_by_role("textbox", name="Enter cohort name or ID...").click()
    page.get_by_role("textbox", name="Enter cohort name or ID...").fill("test")
    page.get_by_role("textbox", name="Enter cohort name or ID...").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Enter cohort name or ID...").fill("rk")
    page.get_by_role("textbox", name="Enter cohort name or ID...").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Enter cohort name or ID...").fill("demo rk")
    page.get_by_role("textbox", name="Enter cohort name or ID...").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Enter cohort name or ID...").fill("RK demo")
    page.get_by_role("textbox", name="Enter cohort name or ID...").click()
    page.get_by_role("textbox", name="Enter cohort name or ID...").press("ControlOrMeta+a")
    page.get_by_role("textbox", name="Enter cohort name or ID...").fill("2007")
    page.get_by_role("textbox", name="Enter cohort name or ID...").press("Enter")
    with page.expect_popup() as page1_info:
        page.get_by_role("link", name="Test RK").click()
    page1 = page1_info.value
    page1.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(5).click()
    page1.get_by_role("textbox").fill("")
    page1.get_by_text("CancelSave Changes").click()
    page1.locator("div").filter(has_text=re.compile(r"^Edit cohortStartDate$")).click()
    page1.get_by_text("cohortStartDate", exact=True).click()
    page1.get_by_role("textbox").press("Tab")
    page1.get_by_role("textbox").fill("2026-07-01T00:00")
    page1.get_by_role("button", name="Save Changes").click()
    page1.get_by_role("button", name="Dates").click()
    page1.get_by_role("cell", name="-04-10T00:00").get_by_role("textbox").fill("2026-01-01T00:00")
    page1.get_by_role("button", name="Save date").click()
    page1.get_by_text("Important date updated").click()
    page1.get_by_text("Important date updated").click()
    page1.get_by_text("Important date updated").click()
    page1.get_by_role("button", name="Course Onboarding").click()
    page1.get_by_role("button", name="#124 Batch #").click()
    page1.get_by_role("textbox", name="Search batches...").fill("demo")
    page1.get_by_role("button", name="#124 Demo-IIT-ropar").nth(1).click()
    page1.get_by_text("LMS Section IDs (Fallback) *(multi-select)Default sections used when the fee-").click()
    page1.locator(".space-y-2").first.click()
    page1.locator(".p-4 > div:nth-child(5)").click()
    page1.locator(".p-4.space-y-4").click()
    page1.locator(".p-4.space-y-4").click()
    page1.get_by_role("button", name="#9367").click()
    page1.locator(".p-4.space-y-4").click()
    page1.get_by_role("button", name="#9367").click()
    page1.locator(".p-4 > div:nth-child(5)").click()
    page1.locator(".p-4.space-y-4").click()
    page1.locator("div").filter(has_text="Course PlatformsCourse").nth(4).click()
    page1.get_by_role("button", name="#8395 DEMO_FOR_NPS_CHECK").click()
    page1.get_by_text("LMS Section IDs (Fallback) *(").click()
    page1.get_by_text("Default sections used when").click()
    page1.get_by_role("button", name="Add sections...").click()
    page1.get_by_role("button", name="#9690 Cohort B - Attempt 2").click()
    page1.locator(".p-4.space-y-4").click()
    page1.get_by_role("button", name="Done (2 selected)").click()
    page1.locator(".space-y-2").first.click()
    page1.get_by_role("button", name="Add sections for After Full").click()
    page1.get_by_role("textbox", name="Search sections for After").fill("agree")
    page1.get_by_role("textbox", name="Search sections for After").press("ControlOrMeta+a")
    page1.get_by_role("textbox", name="Search sections for After").fill("all")
    page1.get_by_role("textbox", name="Search sections for After").press("ControlOrMeta+a")
    page1.get_by_role("textbox", name="Search sections for After").fill("")
    page1.get_by_role("button", name="#8152 Demo-IIT-ropar- testing").click()
    page1.get_by_role("button", name="#8395 DEMO_FOR_NPS_CHECK").click()
    page1.locator("div").filter(has_text=re.compile(r"^Done \(2 selected\)$")).click()
    page1.locator(".p-4 > div:nth-child(5)").click()
    page1.get_by_text("StudentAdd sections for").click()
    page1.get_by_role("button", name="Add sections for Student...").click()
    page1.get_by_role("button", name="#9367").click()
    page1.get_by_role("button", name="Done (1 selected)").click()
    page1.get_by_text("Working Professional", exact=True).click()
    page1.get_by_text("Working ProfessionalAdd").click()
    page1.get_by_role("button", name="Add sections for Working").click()
    page1.get_by_role("button", name="Add sections for Working").click()
    page1.get_by_role("button", name="#3124 demo_iit_ropar Active").click()
    page1.get_by_role("button", name="Done (1 selected)").click()
    page1.get_by_text("After Secure Seat Section IDs(optional)Sections used when the LMS account is").click()
    page1.get_by_text("After Secure Seat Section IDs(optional)Sections used when the LMS account is").click()
    page1.get_by_role("button", name="Add sections for After Secure").click()
    page1.get_by_role("button", name="#8002 Program Onboarding -").click()
    page1.get_by_role("button", name="Done (1 selected)").click()
    page1.get_by_role("button", name="Save LMS Settings").click()
    page1.get_by_text("LMS settings saved").click()
    page1.locator("[id=\"4\"]").click()
    page1.locator("[id=\"5\"]").click()
    page1.locator("[id=\"6\"]").click()
    page1.locator("[id=\"7\"]").click()
    page1.locator("div").filter(has_text=re.compile(r"^Enable Kit$")).first.click()
    page1.locator("[id=\"switch::rb::control\"]").click()
    page1.locator("[id=\"switch::rb::control\"]").click()
    page1.get_by_text("Field updated successfully").click()
    page1.locator("div").filter(has_text=re.compile(r"^Disable Welcome Kit T-Shirt Question$")).nth(1).click()
    page1.locator("div").filter(has_text=re.compile(r"^Disable Welcome Kit T-Shirt Question$")).first.click()
    page1.locator("[id=\"switch::rc::control\"]").click()
    page1.locator("[id=\"switch::rc::control\"]").click()
    page1.get_by_text("Error updating field").click()
    page1.get_by_text("Error updating field").click()
    page1.get_by_role("textbox", name="Enter manager ID").click()
    page1.locator("div").filter(has_text=re.compile(r"^Manager ID \*$")).click()
    page1.get_by_role("textbox", name="Enter manager ID").dblclick()
    page1.get_by_role("textbox", name="Enter manager ID").press("ControlOrMeta+a")
    page1.get_by_role("textbox", name="Enter manager ID").fill("")
    page1.locator("div").filter(has_text=re.compile(r"^Manager ID \*$")).click()
    page1.get_by_role("textbox", name="Enter manager ID").click()
    page1.get_by_role("textbox", name="Enter manager ID").fill("55486")
    page1.locator("div").filter(has_text=re.compile(r"^Manager ID \*$")).click()
    page1.get_by_role("button", name="Save LMS Settings").click()
    page1.get_by_text("LMS settings saved").click()
    page1.get_by_text("Field updated successfully").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
