import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page.goto("https://admissions-admin.masaischool.com/iit/cohort-management/2007")
    page.get_by_text("Test RKView PresentationCopy PresentationUpdate PresentationClone CohortView").click()
    page.get_by_role("button", name="Course Onboarding").click()
    page.get_by_role("button", name="#124 Batch #").click()
    page.get_by_role("textbox", name="Search batches...").fill("iitmd-dm")
    page.get_by_role("button", name="#289 IITMD-DM-EN-I-2608 Pre-").click()
    page.get_by_role("button", name="#289 Batch #").click()
    page.get_by_role("textbox", name="Search batches...").fill("demo")
    page.get_by_role("button", name="#124 Demo-IIT-ropar").click()
    page.get_by_role("button", name="Course Onboarding").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).first.click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).first.click()
    page.get_by_role("button", name="Add sections...").click()
    page.get_by_role("button", name="#9367").click()
    page.get_by_role("button", name="#9254 CHECK -").click()
    page.get_by_role("button", name="Done (2 selected)").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(2).click()
    page.get_by_role("button", name="Add sections for After Full").click()
    page.get_by_role("button", name="#8395 DEMO_FOR_NPS_CHECK").click()
    page.get_by_role("button", name="#8152 Demo-IIT-ropar- testing").click()
    page.get_by_role("button", name="#3124 demo_iit_ropar Active").click()
    page.get_by_role("button", name="Done (3 selected)").click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(5).click()
    page.get_by_role("button").filter(has_text=re.compile(r"^$")).nth(5).click()
    page.get_by_role("button", name="Add sections for Student...").click()
    page.get_by_role("button", name="#9443 Program Onboarding -").click()
    page.get_by_role("button", name="Done (1 selected)").click()
    page.get_by_text("#3124demo_iit_ropar#").click()
    page.locator("div:nth-child(2) > span:nth-child(2) > .ml-0\\.5").click()
    page.locator(".space-y-2 > div:nth-child(3) > .flex.flex-wrap > .inline-flex > .ml-0\\.5").click()
    page.get_by_role("button", name="Add sections for Working").click()
    page.get_by_role("button", name="#9629 Practice & Assignment (").click()
    page.get_by_role("button", name="Done (1 selected)").click()
    page.locator(".space-y-1\\.5 > .space-y-1\\.5 > .flex.flex-wrap > span:nth-child(2) > .ml-0\\.5").click()
    page.locator(".space-y-1\\.5 > .space-y-1\\.5 > .flex.flex-wrap > .inline-flex > .ml-0\\.5").click()
    page.get_by_role("button", name="Add sections for After Secure").click()
    page.get_by_role("button", name="#9426 LMS Walkthrough - Web").click()
    page.get_by_text("After Secure Seat Section IDs(optional)Sections used when the LMS account is").click()
    page.get_by_role("button", name="Save LMS Settings").click()
    page.get_by_text("LMS settings saved").click()
    page.get_by_text("Field updated successfully").click()
    page.locator("[id=\"3\"]").click()
    page.locator("[id=\"4\"]").click()
    page.locator("[id=\"5\"]").click()
    page.get_by_text("LMS Batch ID *#124Batch #").click()
    page.get_by_role("textbox", name="Search batches...").fill("demo")
    page.get_by_role("button", name="#124 Demo-IIT-ropar").nth(1).click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
